name: nvidia-core22
base: core22
adopt-info: version
summary: NVIDIA and Mesa libraries for core22 snaps
description: |
  Content snap that provides NVIDIA and Mesa libraries for `base:
  core22` snaps.
compression: lzo
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  apis:
    # This provides the essential APIs
    #   o libGL.so.0
    #   o libEGL.so.1
    #   o libva.so.2
    #   o libvulkan.so.1
    #   o libgbm.so.1
    #
    plugin: nil
    stage-packages:
      - libgl1
      - libegl1
      - libgles2
      - libvulkan1
      - libgbm1
    prime:
      - usr/lib
      - usr/share/glvnd

  va:
    # Video Acceleration API
    #   o libva.so.2
    plugin: nil
    stage-packages:
      - libva2
    prime:
      - usr/lib

  dri:
    # Userspace drivers
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - va-driver-all
      - vdpau-driver-all
      - libvdpau-va-gl1
      - mesa-vulkan-drivers
      - libglx-mesa0
    prime:
      - usr/lib
      - usr/share/vulkan
      - usr/share/drirc.d
    override-stage: |
      sed -i 's@/usr/lib/[a-z0-9_-]\+/@@' ${CRAFT_PART_INSTALL}/usr/share/vulkan/*/*.json
      craftctl default

  x11:
    # X11 support (not much cost to having this)
    plugin: nil
    stage-packages:
      - libglx0
      - libva-x11-2
      - libx11-xcb1
      - libxau6
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-present0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb1
      - libxdamage1
      - libxdmcp6
      - libxshmfence1
    prime:
      - usr/lib
      - usr/share/X11

  wayland:
    # Wayland support (not much cost to having this)
    plugin: nil
    stage-packages:
      - libwayland-client0
      - libwayland-egl1
      - libwayland-server0
      - libnvidia-egl-wayland1
    prime:
      - usr/lib
      - usr/share/egl/egl_external_platform.d

  nvidia:
    plugin: nil
    stage-packages:
      - libnvidia-egl-wayland1
      - libnvidia-cfg1-515-server
      - libnvidia-common-515-server
      - libnvidia-compute-515-server
      - libnvidia-decode-515-server
      - libnvidia-encode-515-server
      - libnvidia-extra-515-server
      - libnvidia-gl-515-server
      - libnvidia-fbc1-515-server
    prime:
      - etc/OpenCL
      - usr/lib
      - usr/share/glvnd
      - usr/share/egl
      - usr/share/nvidia
      - usr/share/vulkan

  version:
    plugin: nil
    override-pull: |
      set -x
      craftctl set version="$(
        LANG=C
        apt-cache policy libnvidia-common-515-server | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p' | tr -d '\n'
        echo -n "+mesa"
        apt-cache policy libgl1-mesa-dri | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'
      )"

  file-list:
    after:
    - apis
    - dri
    - va
    - x11
    - wayland
    - nvidia
    plugin: nil
    override-prime: |
      mkdir -p ${CRAFT_PRIME}/snap
      (
        cd ${CRAFT_PART_INSTALL}/../..
        # All the cruft coming from stage packages, but not actually staged
        find $( ls -d */install/{etc,usr/{bin,share/{bug,doc,lintian,man}}} ) -type f,l | cut -d/ -f3-
        cd ${CRAFT_PRIME}
        # Everything that is indeed staged
        find usr -type f,l
      ) | sort -u > ${CRAFT_PRIME}/snap/${CRAFT_TARGET_ARCH}.list

  scripts:
    after: [file-list]
    plugin: dump
    source: scripts

slots:
  graphics-core22:
    interface: content
    source:
      read:
        # Required at the top-level by graphics-core22
        - $SNAP/bin
        - $SNAP/usr/share/drirc.d
        - $SNAP/usr/share/X11

        # Internal, pointed at by the above wrapper
        - $SNAP/etc
        - $SNAP/usr/lib
        - $SNAP/usr/share
